### ISSUE TITLE
Commands screwing with Display Module

### ISSUE THREAD

**Issue by Spartan322** [Arkhist/Hacknet-Pathfinder#10]
So probe and login are the only commands acting appropriately, pull up the probe or login screens on the Display Module, however nothing else is working.

Vanilla commands aside from disconnect/dc report to the terminal but don't perform Display Module operations, leaving at the normal connected to a computer screen, disconnect/dc simply force connect you back to the player's computer, even if you're already connected to to it when you do the command.

Custom commands however just make the Display Module stop displaying upon completion

All button actions related to those commands operate the same way.

**Comment by Arkhist** [comment]
Fixed.
