### ISSUE TITLE
Mod dependencies check in execution folder

### ISSUE THREAD

**Issue by Arkhist** [Arkhist/Hacknet-Pathfinder#12]
https://github.com/lugia19/HacknetIRCLink
I fixed this mod a few minutes ago, and it needs to have its dependencies (ChatSharp.dll) in the .exe folder. How to make so that the dependencies are checked inside the mod folder ?

**Comment by Spartan322** [comment]
The way we did mods, there is no way to do non-mod dependencies in the mod folder, I was thinking of making a lib/dep folder if you needed it and allowing players to provide that folder and load it that way. (Nice thing about folders in all OSes is they auto merge if named the same, so as long as two dependencies aren't named the same and the dependencies don't have the same namespaces, it would be fine)

**Comment by Spartan322** [comment]
42c9c6d3a411bbca7141dc534cb1b0fa70632c2a should allow this type of behavior in Mods/deps
