### ISSUE TITLE
CommandManager.OrigProgramListInit throws unconditional NotImplementedException

### ISSUE THREAD

**Issue by PrincessRTFM** [Arkhist/Hacknet-Pathfinder#144]
After fiddling with a simple mod idea, I launched my game to see this:
```
[Error  :   BepInEx] Error loading [Foxnet 1.0.0]: System.NotImplementedException: The method or operation is not implemented.
   at Pathfinder.Command.CommandManager.OrigProgramListInit()
   at Pathfinder.Command.CommandManager.RebuildAutoComplete()
   at Pathfinder.Command.CommandManager.RegisterCommand(String commandName, Action`2 handler, Boolean addAutocomplete, Boolean caseSensitive)
   at FoxyHacknet.Foxnet.Load()
   at BepInEx.Hacknet.HacknetChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in D:\a\Hacknet-Pathfinder\Hacknet-Pathfinder\BepInEx.Hacknet\HacknetChainloader.cs:line 75
   at BepInEx.Bootstrap.BaseChainloader`1.Execute()
```

Inspecting the `CommandManager.OrigProgramListInit()` method in VS showed me this:
```
[MethodImpl(MethodImplOptions.NoInlining)]
[HarmonyReversePatch(/*Could not decode attribute arguments.*/)]
[HarmonyPatch(typeof(ProgramList), "init")]
private static void OrigProgramListInit() {
	throw new NotImplementedException();
}
```

Only the first command registered is successful, because at that point the exception is thrown and no further commands are added. Is this intentional? If so, is a fix planned?

**Comment by Windows10CE** [comment]
Could you send the entire log file? Should be at `BepInEx/LogOutput.log`

**Comment by PrincessRTFM** [comment]
[Full log file](https://github.com/Arkhist/Hacknet-Pathfinder/files/7804737/LogOutput.log) without try/catch. Possibly worth noting, if I just put a try/catch block around the command registration call, the commands do all actually register successfully, and the game loads.

**Comment by Windows10CE** [comment]
Your plugin is loading before PathfinderAPI does, use https://docs.bepinex.dev/api/BepInEx.BepInDependency.html to tell it to load yours after Pathfinder.

**Comment by SoundOfScooting** [comment]
> Your plugin is loading before PathfinderAPI does, use https://docs.bepinex.dev/api/BepInEx.BepInDependency.html to tell it to load yours after Pathfinder.

That currently won't work if the plugin is used in an extension and not globally (it won't detect PathfinderAPI and will not load).

**Comment by PrincessRTFM** [comment]
This is a global plugin, so that'll be fine. I didn't see any mention of that in the [documentation for getting started](https://arkhist.github.io/Hacknet-Pathfinder/mod/start/), so that's why I didn't have it before. Thank you for the help!
