### ISSUE TITLE
Computer.portsNeededForCrack seems to be one less than the actual game value

### ISSUE THREAD

**Issue by PrincessRTFM** [Arkhist/Hacknet-Pathfinder#149]
When reading the number of ports that need to be open to PortHack a computer, the returned value seems to be one less than the _actual_ value. On the player's computer, `probe` shows that four ports are needed, but `os.thisComputer.portsNeededForCrack` returns `3`, for example:

![2022-01-16 18 06 44 - Hacknet](https://user-images.githubusercontent.com/8753564/149681907-928ab5a2-ecb9-44d4-95f0-990cf785b895.png)

**Comment by SoundOfScooting** [comment]
This is how the base game was designed. It correctly uses the value by adding 1 to it when needed.

**Comment by PrincessRTFM** [comment]
That's absolutely terrible, but I guess I'll just have to do the same thing in my plugin.
