### ISSUE TITLE
*nix

### ISSUE THREAD

**Issue by Sigma-One** [Arkhist/Hacknet-Pathfinder#15]
Would a Linux/Mac port be possible?

**Comment by Spartan322** [comment]
We're working on making a usable Linux/Mac port, for now if you want to play with Unix systems, download a mono package or so, run the patcher with mono like `mono PathfinderPatcher.exe` in the directory of Hacknet, then copy the Hacknet.bin executable file and rename the `Hacknet` to `HacknetPathfinder`, nothing else however, leave the rest of the bits of that file's name the same, then you can run the modded game by running the new HacknetPathfinder.bin file.

**Comment by Arkhist** [comment]
Pathfinder runs on GNU/Linux systems without problems.
