### ISSUE TITLE
Pathfinder API attempts invalid patches in GOG version

### ISSUE THREAD

**Issue by Fr4Ckt3r** [Arkhist/Hacknet-Pathfinder#191]
installed pathfinder via installer
https://pastebin.com/XX22Rgpa

**Comment by Arkhist** [comment]
Hello, what Hacknet version are you using? (Steam, GOG, other; and version number)

**Comment by Fr4Ckt3r** [comment]
> Hello, what Hacknet version are you using? (Steam, GOG, other; and version number)

GOG v5.069

**Comment by Arkhist** [comment]
What mods are you using?
Please do drop logs if you have any.

I think the first issue is related to one of our patches being steam-exclusive. As for the mods, I'd like more information.

**Comment by Fr4Ckt3r** [comment]
> What mods are you using? Please do drop logs if you have any.
> 
> I think the first issue is related to one of our patches being steam-exclusive. As for the mods, I'd like more information.

I'm using XMOD. Logs when starting game with it:
https://pastebin.com/DHez2fqK
Commands XMOD adds doesn't seem to work. (didn't check executables tho)

However, i also tried using ZeroDayToolKit (just test if any mods work on my game) (i removed XMOD after adding zeroday)
It seems that ZeroDay's... ehhh... menu thingy? (mod's version next to hacknet version in main menu thing) appears fine, but commands from ZeroDay won't work. (forgot to check executables)
By the way, i am using Windows 11.

**Comment by Arkhist** [comment]
I think the issues you are experiencing with the mods come from the first error in the console.

**Comment by Arkhist** [comment]
#193 Should have fixed it.

Will be in the next release.
