### ISSUE TITLE
Finalize replacement of SAX classes with EventExecutor

### ISSUE THREAD

**Issue by Spartan322** [Arkhist/Hacknet-Pathfinder#28]
And remove all SAX classes and references as well.

Existing References:
- [x] ContentLoaderReplacement (#27)
- [x] DatabaseDaemonHandler (#39)
- [x] HandlerListener (#39)
- [x] MissionInstance (#39)
- [x] MissionUtility (#39)
- [x] SerializableAction (#39)
- [x] Serializablecondition (#39)
- [x] SerializableHandler (#39)

Existing Namespace:
- [x] Sax.Net (Pathfinder/Util/Sax directory) (#39)

Existing Classes:
- [x] SaxProcessor (#39)

**Comment by Fayti1703** [comment]
`ContentLoaderReplacement` is already pretty much SAX-free, minus some unused legacy functions. #27 removes those.

**Comment by Spartan322** [comment]
Alright, I'll correct the ContentLoaderReplacement tick as soon as it gets pulled.
