### ISSUE TITLE
Suggestion: Make command handler inject into help

### ISSUE THREAD

**Issue by Ovyerus** [Arkhist/Hacknet-Pathfinder#6]
Possibly as an optional thing if people want to create hidden commands.
`Hacknet.Helpfile` controls the help command but looks pretty static. Maybe override it so that you can easily inject command help into it.

**Comment by Ovyerus** [comment]
Looking through the command handler code, looks like it is implenented-ish, however trying to use it like that results in a NullReferenceException

**Comment by Spartan322** [comment]
yeah, we're adding to Helpfile.help before it's been initialized, this will probably be fixed with the next release.

**Comment by Spartan322** [comment]
Fixed by 585b731c511e8364e3cab9dfff2be5baf06934a3
