### ISSUE TITLE
Trying to use default executables doesn't work

### ISSUE THREAD

**Issue by Ovyerus** [Arkhist/Hacknet-Pathfinder#7]
When I try to use a default Hacknet executable, I either get `Execution failed` or nothing at all. Have verified that this only happened on Pathfinder as the executables work fine on default unmodified Hacknet. Has happened on old save and brand new save.

**Comment by Spartan322** [comment]
yeah, this might be a problem the threading in the game, when the game runs a thread for a command or program, I've found in some areas, it just hangs the thread to create an event, (though oddly not everywhere within the thread for some reason) gonna need to find out why.

**Comment by Spartan322** [comment]
Should be fixed by 6e6306a26f84a98cca2fb5cb71debdf3014cec0c, 2d5f5842e9d49920e7e38094566fbeb485c8673f, and 15686bf8cedd076a8a84fec4fe8d6f56916570ba
