### ISSUE TITLE
Player Loses playerComp Admin On playerComp IP change

### ISSUE THREAD

**Issue by Windows10CE** [Arkhist/Hacknet-Pathfinder#71]
"I just realized the code checks for computer.adminIP == os.thisComputer.adminIP instead of computer.adminIP == os.thisComputer.ip"

**Comment by Fayti1703** [comment]
Quote is from me, for the record.

**Comment by MaowImpl** [comment]
Is this not intentional? I may have missed something but this sounds intentional to give the player a punishment for failing traces and having to go through the ISP sequence.

**Comment by MaowImpl** [comment]
> 
> 
> Is this not intentional? I may have missed something but this sounds intentional to give the player a punishment for failing traces and having to go through the ISP sequence.

I stand corrected.

**Comment by Windows10CE** [comment]
Fixed with 59235b30254eb044f09d1d1b9c32911740d4bc53
