### ISSUE TITLE
Game crashes when loading a save file for an extension

### ISSUE THREAD

**Issue by Marthenop** [Arkhist/Hacknet-Pathfinder#81]
I tried this with three different extensions. Here is the error:
![SAVE THIS MESSAGE! 7_30_2021 2_49_17 PM](https://user-images.githubusercontent.com/87893125/127700585-ecda9483-5af1-4722-a056-0408e3a3e9e7.png)

**Comment by Windows10CE** [comment]
Could you tell an extension this happens with, and possibly send a save file?

**Comment by Marthenop** [comment]
I tried it with my own extension, and HelSec 1+2
I have tried looking in the normal directories for the save files, but I am unable to locate any of the new save files.

**Comment by Windows10CE** [comment]
On Windows they're in Documents/HacknetPathfinder, on Linux I believe they're in ~/.local/share/HacknetPathfinder

**Comment by Marthenop** [comment]
Thank you, here are the save files:
[savefiles.zip](https://github.com/Arkhist/Hacknet-Pathfinder/files/6909688/savefiles.zip)

**Comment by Windows10CE** [comment]
This should now be fixed with beta 3, if you find any more problems please make another issue
