### ISSUE TITLE
[BaseGame] Handling of missing `url` on `Computer.addWebServer`

### ISSUE THREAD

**Issue by Fayti1703** [Arkhist/Hacknet-Pathfinder#88]
In the base game, forgetting to specify an `url` attribute for the `addWebServer` element causes either a `NullReferenceException` or an `ArgumentNullException`, depending on locale settings (latter for `en-us`, former for everything else).

This could be replaced with an early error in `Replacements/ContentLoader`.

Relevant line:
<https://github.com/Arkhist/Hacknet-Pathfinder/blob/6ab4243/PathfinderAPI/Replacements/ContentLoader.cs#L505>

**Comment by Windows10CE** [comment]
Done with 9d0dcbecf75bb38704aa452accea6797a5f616ed
