### ISSUE TITLE
"Event Listener Call Failed" and blank "Exception:" error

### ISSUE THREAD

**Issue by vrdpulse** [Arkhist/Hacknet-Pathfinder#9]
From oxygencraft's DebugMod. The commands "themeAttack" and "strikerAttack" works for the author, but does throw errors for me. Using latest files "Pathfinder 2.0.1" and "DebugMod 1.7.5b".

![e7](https://cloud.githubusercontent.com/assets/27949018/25371137/9e9b718a-29c1-11e7-8da5-834877684e7f.png)

The author made a custom version that should make this message appear in the console when I enter the specific command "strikerAttack":

![m1](https://cloud.githubusercontent.com/assets/27949018/25371254/5c4908d2-29c2-11e7-9030-d8727080cf5e.png)

But even that won't appear in my end and still throws the error:

![e9](https://cloud.githubusercontent.com/assets/27949018/25371281/8394721e-29c2-11e7-86b8-044d393c52f1.png)

Thank you very much for your time.

**Comment by oxygencraft125** [comment]
Source of DebugMod: https://github.com/oxygencraft/DebugMod

**Comment by Arkhist** [comment]
Do you have Labyrinths installed ?

**Comment by Spartan322** [comment]
Yeah, this is a mod problem when you don't have Labyrinths installed, @oxygencraft125 you need to ensure Labyrinths is installed.
