### ISSUE TITLE
Replace Hacknet port system with a Protocol oriented port system

### ISSUE THREAD

**Issue by Arkhist** [Arkhist/Hacknet-Pathfinder#94]
Hacknet's port system is bound to generate conflicts and is confusing both for mod developers (conflicts) and for extension makers (the port remapping system is cumbersome).

This proposal is to replace Hacknet's port system, oriented around numerical ids, towards a Protocol oriented system around strings.
An extension maker would place in their computer's xml:
`<ProtocolPorts>ftp:21, ssh:22, mycustomport:80</ProtocolPorts>`

Instead of registering a numerical id for a new port, a mod will register a protocol. PortCrackers will use protocols instead of numerical ids. Computers will stop relying on numerical ids and instead use a ProtocolPort dictionary.

This system must be backwards compatible with base game ports.

**Comment by Windows10CE** [comment]
Done with 6947f17e7fcffe1bd42244597d889a8ad9fcf2bd
